-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 11:56:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gallery` (
  `gallery_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`gallery_id`),
  UNIQUE INDEX `gallery_id_UNIQUE` (`gallery_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Collection` (
  `collection_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Gallery_gallery_id` INT NOT NULL,
  PRIMARY KEY (`collection_id`),
  UNIQUE INDEX `collection_id_UNIQUE` (`collection_id` ASC),
  INDEX `fk_Collection_Gallery1_idx` (`Gallery_gallery_id` ASC),
  CONSTRAINT `fk_Collection_Gallery1`
    FOREIGN KEY (`Gallery_gallery_id`)
    REFERENCES `mydb`.`Gallery` (`gallery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `Collection_collection_id` INT NOT NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `company_id_UNIQUE` (`company_id` ASC),
  INDEX `fk_Company_Collection1_idx` (`Collection_collection_id` ASC),
  CONSTRAINT `fk_Company_Collection1`
    FOREIGN KEY (`Collection_collection_id`)
    REFERENCES `mydb`.`Collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Company_company_id` INT NOT NULL,
  `Role_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_User_Company1_idx` (`Company_company_id` ASC),
  INDEX `fk_User_Role1_idx` (`Role_role_id` ASC),
  CONSTRAINT `fk_User_Company1`
    FOREIGN KEY (`Company_company_id`)
    REFERENCES `mydb`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_role_id`)
    REFERENCES `mydb`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Template` (
  `template_id` INT NOT NULL AUTO_INCREMENT,
  `tamplate_file` VARCHAR(255) NOT NULL,
  `Company_company_id` INT NOT NULL,
  PRIMARY KEY (`template_id`),
  UNIQUE INDEX `template_id_UNIQUE` (`template_id` ASC),
  INDEX `fk_Template_Company1_idx` (`Company_company_id` ASC),
  CONSTRAINT `fk_Template_Company1`
    FOREIGN KEY (`Company_company_id`)
    REFERENCES `mydb`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(2,2) NOT NULL,
  `verified` TINYINT NOT NULL,
  `downloads` INT NOT NULL,
  `template_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `Gallery_gallery_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  INDEX `fk_Product_Template1_idx` (`template_id` ASC),
  INDEX `fk_Product_User1_idx` (`user_id` ASC),
  INDEX `fk_Product_Gallery1_idx` (`Gallery_gallery_id` ASC),
  CONSTRAINT `fk_Product_Template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `mydb`.`Template` (`template_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Gallery1`
    FOREIGN KEY (`Gallery_gallery_id`)
    REFERENCES `mydb`.`Gallery` (`gallery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image` BLOB(1) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`image_id`),
  UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image_has_Collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image_has_Collection` (
  `Image_image_id` INT NOT NULL,
  `Collection_collection_id` INT NOT NULL,
  INDEX `fk_Image_has_Collection_Image1_idx` (`Image_image_id` ASC),
  INDEX `fk_Image_has_Collection_Collection1_idx` (`Collection_collection_id` ASC),
  CONSTRAINT `fk_Image_has_Collection_Image1`
    FOREIGN KEY (`Image_image_id`)
    REFERENCES `mydb`.`Image` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Image_has_Collection_Collection1`
    FOREIGN KEY (`Collection_collection_id`)
    REFERENCES `mydb`.`Collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;