@startuml
rectangle products {
    file file_products [
        **product_routes.py**
    ]

    card all_products[
        **/templates/<int:company_identifier>**
        ----
        GET
        ----
        POST
    ]

    card specific_product[
        **/template/<int:company_identifier>/<int:template_identifier>**
        ----
        GET
        ----
        DELETE
    ]
}

file_products --> all_products
file_products --> specific_product

@enduml