@startuml
skinparam minClassWidth 200
skinparam nodesep 20
skinparam ranksep 20
'skinparam linetype ortho

file **template_routes.py** as file_templates #FEFECE {
    rectangle **/templates/<int:company_identifier>** as all_templates #ffffff{
    rectangle "**GET**\n(View company's template metadata)\t\t\t" #Application
    rectangle "<color:grey>**DELETE**\n<color:grey>(NOT IMPLEMENTED)\t\t\t\t\t\t" #lightgrey
    rectangle "**POST**\n(Upload new template to company)\t\t\t\t" #technology
    rectangle "<color:grey>**PUT**\n<color:grey>(NOT IMPLEMENTED)\t\t\t\t\t\t" #lightgrey
    }

    rectangle **/template/<int:company_identifier>/<int:template_identifier>** as specific_template #ffffff{
    rectangle "**GET**\n(Retreive specific company template data)\t\t" #Application
    rectangle "**DELETE**\n(Remove specific company template data)\t\t" #Implementation
    rectangle "<color:grey>**POST**\n<color:grey>(NOT IMPLEMENTED)  \t\t\t\t\t\t" #lightgrey
    rectangle "<color:grey>**PUT**\n<color:grey>(NOT IMPLEMENTED)\t\t\t\t\t\t" as e #lightgrey
    }
}

'file_products -d--> all_products
'file_products ---> specific_product
all_templates --[HIDDEN]-> specific_template

@enduml
