@startuml FTPServerModel
rectangle "FTP Server (Windows 2019)" {
    component A [
        kyndaftp
        |_ 1
          |_ templates
            |_ example.html 
            |_ example2.html
          |_ images
            |_ example.png
            |_ example.jpeg
        |_ 2
          |_ templates
          |_ images
        |_ 3
          |_ etc...
        |_ etc...
    ]
}
note right of A
numbers represent
company IDs
end note
@enduml