@startuml activity diagram downloaden grafisch product
start
->//Medewerker heeft een account, medewerker is ingelogd//;
:beeldbank aanpassen;
if(zit beeldbank vol?) then (ja)
        #orangered:"Error";
        stop
        endif
        ->Nee;
        #palegreen:Upload afbeelding van computer;
stop
@enduml