@startuml activity diagram downloaden grafisch product
start
->//Klant heeft een account,//
//klant is ingelogd in applicatie,//
//klant heeft grafische ontwerp gemaakt//;
repeat
        if (goedgekeurd door Kynda medewerker?) then(Ja)
            #palegreen:Download optie en transactie;
            stop
        endif
        ->Nee;
        #orangered:"Error";
repeat while (Goedkeuring vragen aan Kynda medewerker door hoofdgebruiker)
@enduml